### ISSUE TITLE
Hide the Adbmob Banner Panel while loading

### ISSUE THREAD

**Issue by treviz13** [fuse-compound/Fuse.Firebase#102]
Hey there,

is it Possible to hide the Panel, where the NativeViewHost is till the AdBanner is loaded?
from this:
```
 <Text Value="Ad Next" />
            <NativeViewHost>
                <Firebase.AdMob.GADBannerView Height="90" AdUnitId="ca-app-pub-xxxxxxxxxxxxxxxx/xxxxxxxxxx" />
            </NativeViewHost>
<Text Value="Ad Over" />
```
to something like this:
```
 <Panel ux:Name="adPanel" Visibility="Collapsed">
            <NativeViewHost>
<WhileBusy>
<Change adPanel.Visibility="Visible"/>
</WhileBusy>
                <Firebase.AdMob.GADBannerView Height="90" AdUnitId="ca-app-pub-xxxxxxxxxxxxxxxx/xxxxxxxxxx" />
            </NativeViewHost>
</Panel>
```

I havent found any solution to this :/
Thanks for help :)

**Comment by treviz13** [comment]
Is there no one who had that Problem? :/

**Comment by LuisRodriguezLD** [comment]
Hello, 
I am not sure I understand your question,

If this is about the Ad itself I don't think there is a way to now when the ad was actually loaded.

If this is about hiding/showing elements inside the `NativeViewHost` it is totally possible. Try the following: 

```
<App>
	<StackPanel Alignment="Center" ItemSpacing="60" >
		<Button Text="Hide NativeViewHost">
			<Clicked>
				<Change nvw.Opacity="0" Duration=".2" />
			</Clicked>
		</Button>
		<NativeViewHost ux:Name="nvw">
			<Text Alignment="Center" Value="asdfasdf" />
		</NativeViewHost>
	</StackPanel>
</App>
```

Please let me now if you need more help

**Comment by treviz13** [comment]
Thanks!
It is exactly like hiding elements in native view host. But if the ad is not loaded, there is a white blank panel i want to hide only if this ad is not loaded 🙊 I think then it is AT this moment Not possible? 🙊

**Comment by treviz13** [comment]
I have solved this Problem like this:

> <Panel Alignment="Bottom"    >
> 	<Rectangle Layer="Background" Fill="#00009900">
> 	</Rectangle>
> 									
> 								
> 	<NativeViewHost Dock="Bottom" RenderToTexture="false">
> 	    <Firebase.AdMob.GADBannerView AdUnitSize="SMART_BANNER" AdUnitId="{Resource adMobBannerForenTopicSingle}"  AdUnitIdiOS="{Resource adMobBannerForenTopicSingleIOS}" />
> 	</NativeViewHost>
> </Panel>
Now the Panel is only visible, when the ad is loaded :)

**Comment by LuisRodriguezLD** [comment]
Can you share your fix? Maybe someone could need it on the future

**Comment by treviz13** [comment]
Sorry, I didn´t see, that I have not pasted the code :D 
```
<Panel Alignment="Bottom"    >
	<Rectangle Layer="Background" Fill="#00009900">
	</Rectangle>
									
	<NativeViewHost  RenderToTexture="false">							
	<Firebase.AdMob.GADBannerView AdUnitSize="SMART_BANNER" AdUnitId="{Resource adMobBannerGeneralCase}" AdUnitIdiOS="{Resource adMobBannerGeneralCaseIOS}"/>
	</NativeViewHost>
</Panel>
```
