### ISSUE TITLE
Having access to "real" user id when login with fb

### ISSUE THREAD

**Issue by zaulin** [fuse-compound/Fuse.Firebase#103]
**Describe the solution you'd like**
It would be useful to have access to the user id when logged with fb. This is useful to, for example, get a larger user picture with a server process

**Describe alternatives you've considered**
The only alternative I've found is to make another request with another auth token to get "me" info

**Additional context**
Fb changed his privacy policy so the userid returned by fb to firebase is not the "real" user id but a app-scoped id

**Comment by LuisRodriguezLD** [comment]
Firebase has a way to get the providers (in this case Facebook) data. See [here](https://firebase.google.com/docs/auth/ios/manage-users?authuser=0#get_a_users_provider-specific_profile_information).

I have exposed this to Fuse.
Try [this branch](https://github.com/fuse-compound/Fuse.Firebase/tree/get-providers-data) and let me know what you think.

You can use in the following way
```js
var FirebaseUser = require("Firebase/Authentication/User");
console.log(FirebaseUser.providerData)

```

Note: I am really bad at Java so the Android part is untested
