### ISSUE TITLE
Cant compile 

### ISSUE THREAD

**Issue by iicd2386cd** [fuse-compound/Fuse.Firebase#15]
hi, i did everything from your step by step tut. 
But when i try to compile project i got this : 

```
* What went wrong:
Execution failed for task ':app:compileAuthExampleArmeabi-v7aDebugSharedLibraryAuthExampleMainCpp'.
> Cannot create file. 'C:\Users\dAREKfff\Desktop\Fuse.Firebase-master\AuthExample\build\Android\Debug\AuthExampl
ild\intermediates\objectFiles\armeabi-v7aDebugSharedLibrary\AuthExampleMainCpp\9q25mjik6y9ecin67206s43oz\_root.A
le_FuseNavigationDirectNavigation_Active_Property.o' exceeds windows path limitation of 260 character.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by aToO57** [comment]
> exceeds windows path limitation of 260 character.

Try to put your project direct on root
(ex: C:/yourproject)

**Comment by cbaggers** [comment]
There is also a bit of dark magic you can try :) 

Add `--set:AltBuildPath="C:/temp/` to your arguments to build

**Comment by cbaggers** [comment]
Closing this. We have made some changes internally to minimize our path length. Sadly android still mandates crazy build directory structures
