### ISSUE TITLE
Facebook Login Aborting

### ISSUE THREAD

**Issue by changalberto** [fuse-compound/Fuse.Firebase#30]
@cbaggers Any clue why Facebook login is failing? Here's a screencast: http://take.ms/1ZsW3

**Comment by changalberto** [comment]
@bolav If you have some time and Bagger doesn't get to this, do you think you can shed some light as to what might be causing facebook login to fail?

Note: I've already tried login in with test users accounts and dev accounts that have access to this app in dev mode.

**Comment by bolav** [comment]
Please test my fork: https://github.com/bolav/Fuse.Firebase/

**Comment by changalberto** [comment]
@bolav Your fork works. Thanks!

**Comment by cbaggers** [comment]
@bolav are thoses fixes mergable? I'd love to get them in if we can

**Comment by bolav** [comment]
@cbaggers Yes.

**Comment by LuisRodriguezLD** [comment]
I believe PR #33 from Bolav fixed it
