### ISSUE TITLE
package com.google.android.gms.task doesn't exists

### ISSUE THREAD

**Issue by krispassa** [fuse-compound/Fuse.Firebase#35]
Having problem compiling. Keeps saying that com.google.android.gms.task doesn't exists
![1212](https://cloud.githubusercontent.com/assets/5103187/23346439/e510f994-fc5f-11e6-82f5-c27e644dbbaf.PNG)

**Comment by cbaggers** [comment]
I'll look at this asap. Thanks for reporting

**Comment by krispassa** [comment]
I am no longer getting previous error. I am getting the error bellow.
![2](https://cloud.githubusercontent.com/assets/5103187/23373562/284d8a0c-fce6-11e6-880b-ff6720856df9.PNG)

**Comment by cbaggers** [comment]
I'm getting the following errors (different to yours). How are you building this? (as in what command line options are you passing?)

**Comment by cbaggers** [comment]
Please run `./build/Android/Debug/build.sh` and paste the result here

**Comment by krispassa** [comment]
Sorry, I am new at this. How do I run that command on window os

**Comment by cbaggers** [comment]
Woops, didnt notice it was windows :) there is a `build.bat` file in `build\Android\Debug\` running that will be a bit more verbose and may have some clues

**Comment by cbaggers** [comment]
Also, what command are you using to build this?

**Comment by krispassa** [comment]
@echo off
pushd "%~dp0AuthExample\app\src\main"
set ANT_DIR=C:\ProgramData\Uno\SDKs\Ant
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_92

echo ## 1/2: libAuthExample.so
call makew -s -j %NUMBER_OF_PROCESSORS% %* || goto ERROR

echo.
echo ## 2/2: AuthExample.apk
if exist "%ANT_DIR%\bin\ant.bat" (
    set "ANT=%ANT_DIR%\bin\ant.bat"
) else (
    echo ERROR: ant.bat was not found in "%ANT_DIR%\bin"
    goto ERROR
)

call "%ANT%" debug || goto ERROR

cd "%~dp0"
C:\Users\Passa\AppData\Local\Fusetools\Fuse\App\app-0.35.0.10867\uno.exe cp AuthExample/app/src/main/bin/AuthExample-debug.apk AuthExample.apk || goto ERROR

popd && exit /b 0

:ERROR
popd && exit /b 1

**Comment by cbaggers** [comment]
@krispassa I meant like `uno build .etc etc`

**Comment by cbaggers** [comment]
Closing as inactive. Happy to reopen if needed
