### ISSUE TITLE
clicking Google button login makes xcode crash

### ISSUE THREAD

**Issue by zaulin** [fuse-compound/Fuse.Firebase#40]
Hi,

after the last changes i got the project running and successfully logged in with facebook but Xcode crashed when i clicked the google login button.

Fuse 0.35

**Comment by cbaggers** [comment]
XCode crashes? That's worrying. Are you using a beta of XCode?

**Comment by cbaggers** [comment]
> zaulin
> a minute ago
> No.
> XCode 8.2.1 (8C1002)

**Comment by cbaggers** [comment]
Very strange. I'll go test this now.

**Comment by cbaggers** [comment]
No luck. It works fine here. The fact that XCode crashes is very strange, nothing on the phone should crash xcode, it sounds like a bug there. Maybe see if there are any updates you can install

**Comment by zaulin** [comment]
Following the instructions I ran: $ fuse build -t=iOS -DCOCOAPODS -d

and then used emulator to test both fb and google login.

There are updates i cannot install as i'm stuck on 10.11.6 due to hardware :)

**Comment by cbaggers** [comment]
Just to clarify, does all of XCode crash or just the app in the emulator?

**Comment by zaulin** [comment]
I meant that when running the app in the emulator and clicking the google login button Xcode raised an exception

![captura de pantalla 2017-04-25 a las 14 19 29](https://cloud.githubusercontent.com/assets/20723271/25384888/467981a8-29c2-11e7-8d20-2b4c15d6b18f.png)

**Comment by cbaggers** [comment]
Ah yeah, that's a very different issue than I thought :p

**Comment by LuisRodriguezLD** [comment]
I just tested this and it works great on latest master, please reopen if it error comes up again
