### ISSUE TITLE
Fb login not showing email

### ISSUE THREAD

**Issue by zaulin** [fuse-compound/Fuse.Firebase#44]
Hi,

When i login with fb i get my name, my picture but where it's supposed to appear the email it always show "-".

![captura de pantalla 2017-04-25 a las 23 04 39](https://cloud.githubusercontent.com/assets/20723271/25408098/2205d8ee-2a0d-11e7-8f39-c53a8b648223.png)

**Comment by cbaggers** [comment]
Could it be related to this? https://stackoverflow.com/questions/37522582/empty-email-field-of-firebase-auth-user-using-facebook-login-integration-fireba

**Comment by zaulin** [comment]
it seems so!! thnx!
