### ISSUE TITLE
Firebase Realtime Database

### ISSUE THREAD

**Issue by mkihuha** [fuse-compound/Fuse.Firebase#47]
This a really awesome project and I am more than just impressed as a developer. I am already implementing it into a project that am about to launch and it might just become the defacto module(s) for me going forward.

However, I was wondering if you have started looking into Firebase's Realtime Database as I would like to extend the user details captured during the first time a user logs into an app using Firebase.Authentication. The Firebase documentation confirms that the user details (user ID, email and photoURL) are stored in a different location from the Realtime Database and as such developers cannot include additional fields when they want to capture specific user details e.g. phone number. As a work around, a developer would be required to extend this via their Realtime Database.

I'll therefore appreciate it if you could guide me on how best I can approach this.

**Comment by cbaggers** [comment]
I have merged in the work bolav has done on the database feature. It's doesnt have documentation or an example yet though. I will get to those when I can.

**Comment by LuisRodriguezLD** [comment]
this [commit](https://github.com/jesusmartinoza/Fuse.Firebase/commit/c0581c33671a08eab91be4abec4c9951b56414c0) has what you need

**Comment by LuisRodriguezLD** [comment]
We have [docs](https://github.com/fuse-compound/Fuse.Firebase#listen-for-data-event) now
