### ISSUE TITLE
Package Request: Fuse.Graphcool

### ISSUE THREAD

**Issue by changalberto** [fuse-compound/Fuse.Firebase#48]
I'm not sure where to request this. Thought I should ask here instead since it's similar.

Could you also create a Fuse package that handles https://www.graph.cool/?
This is very similar to Firebase except that it is a GraphQL version of it.

Would also be cool if you can create an apollo client for Fuse.
http://dev.apollodata.com/

Let me know your thoughts.

Thanks!

**Comment by LuisRodriguezLD** [comment]
This are both _very_ cool packages. 
I personally find many uses of them.

Specifically Apollo would be great to have in [Fuse Libs](https://github.com/fuse-open/fuselibs)
