### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by LuisRodriguezLD** [fuse-compound/Fuse.Firebase#50]
Not sure if Firebase/Facebook (or maybe Fuse) updated something on their end but a I _think_ some stuff is broken.

I can sign up and log in using email and password but I can't sign out. To be more precise I _can_ sign out (I know this because trying to re-authenticate tells me there is no user signed in) but the page stays the same.

Logging in using Facebook works but stays on the home screen, it does not get redirected.
Are these known issues? Kind of need this repo for a big project.

**Comment by cbaggers** [comment]
Hi Luis, I'll take a look. Sorry, I've just been buried in work so firebase hasnt been top of the list for a long time (which sucks as it's important to a bunch of us)

**Comment by LuisRodriguezLD** [comment]
I _totally_ understand. To be honest **Fuse** is a great tool for app development, not that I have mastered it but it's quite easy to get the hang of it (I'm designer BTW) but I find it moderately hard to use Foreign Code which is why I _really_ love this kind of repos. Sometimes I try to analyze how it's built but no luck. 

Anyway, thanks for all the hard (and extra) work you do for the community! I am pretty sure I speak for a lot of Fusers. We really appreciate it.

**Comment by cbaggers** [comment]
Tested on iOS and Android and email login appears to be working. Try pulling the latest commits and see if that helps

**Comment by LuisRodriguezLD** [comment]
What about Facebook login?

**Comment by LuisRodriguezLD** [comment]
Never mind, it's working now. thank you very much!!
