### ISSUE TITLE
iOS admob banner offset

### ISSUE THREAD

**Issue by ckarmy** [fuse-compound/Fuse.Firebase#51]
The AdMob example work perfect on Android but in iOS the position of the banner have a offset! How can I solve this?

Here is an example:
![whatsapp image 2017-08-22 at 13 38 28](https://user-images.githubusercontent.com/10090783/29577726-e637733e-8742-11e7-8c5c-1c686d2ecb9e.jpeg)

**Comment by fusebuild** [comment]
The forum thread [iOS admob banner offset](https://www.fusetools.com/community/forums/bug_reports/ios_admob_banner_offset) posted by Cristian Karmy was linked to this issue.

**Comment by cbaggers** [comment]
Hmm I'm going to try rope in some help with this one I'm not getting far debugging this
