### ISSUE TITLE
Fuse.JSON missing

### ISSUE THREAD

**Issue by Bahle** [fuse-compound/Fuse.Firebase#62]
I cannot build the Firebase Database project because a Fuse.JSON dependency is non-existent.

Please help

**Comment by jesusmartinoza** [comment]
Right, Idk why this is not implemented in master 🤔 
For now just copy/clone the repo https://github.com/ollef/Fuse.JSON in the root of Fuse.Firebase

**Comment by Bahle** [comment]
Thanks a million mate! You helped massively.

**Comment by LuisRodriguezLD** [comment]
We have now include Fuse.JSON inside the repo, you no longer need to import it manually
