### ISSUE TITLE
'Firebase.DataBase.JS.DatabaseModule' was not found 

### ISSUE THREAD

**Issue by samux1996** [fuse-compound/Fuse.Firebase#65]
Hi,

I'm starting to use Firebase but I have a problem. When testing the app on my android, it gives an error saying "'Firebase.DataBase.JS.DatabaseModule' was not found".

When trying to use the Auth example, after performing all the settings, the Google login button and Facebook do not appear, and when trying to use my phone, the error "Firebase.Authentication.JS.AuthenticationModule" appears again.

I'm using the last version of Fuse.

**Comment by LuisRodriguezLD** [comment]
Hello Sam, we have made a couple of changes on the examples, can you try again on the master branch?

Also, we have updated [our docs](https://github.com/fuse-compound/Fuse.Firebase/blob/master/docs/index.md) too ;)

**Comment by samux1996** [comment]
It's working now, thanks!!! :D

**Comment by LuisRodriguezLD** [comment]
Always happy to help
