### ISSUE TITLE
Push not working properly (SDK: TargetVersion: 26)

### ISSUE THREAD

**Issue by ckarmy** [fuse-compound/Fuse.Firebase#69]
When I receive a push notification on Android and my app is open I receive the push on push.on(“receivedMessage”, function(payload)…

But when my app is on background or closed I dont receive the push in my notification bar!

The problem start when I set
"SDK": { "BuildToolsVersion": "23.0.1", "CompileVersion": 23, "MinVersion": 16, "TargetVersion": 26 }
I need to set this because from August 2018 the minimum TargetVersion would be the 26 (https://github.com/fusetools/fuse-releases/issues/1#issuecomment-390462236)
  
Maybe is this: https://stackoverflow.com/questions/43093260/notification-not-showing-in-oreo

Its possible to integrate this on Firebase Notifications?

**Comment by LuisRodriguezLD** [comment]
Interesting, well according to that answer:

> In Android O it's a must to use a channel with your Notification Builder

How are you building/sending your push notification?

**Comment by LuisRodriguezLD** [comment]
Found it, [this](https://github.com/fuse-compound/Fuse.Firebase/blob/master/src/Firebase.Notifications.Android/Android/PushNotificationReceiver.java#L200-L208) is where the channel ID should go.

We have a couple of months before that becomes obligatory. 
Quite simple to fix, however I do not have an Android. Could you help me test it?

**Comment by ckarmy** [comment]
@LuisRodriguezLD No, I have the same problem...

> push.on(“receivedMessage”, function(payload)…

Work but I dont see the notification on the **notificationBar**
