### ISSUE TITLE
[IOS] FirebaseAnalytics/FIRApp.h' file not found

### ISSUE THREAD

**Issue by gtoto007** [fuse-compound/Fuse.Firebase#78]
I have fuse 1.8.1 - Mac OS

I tried to launch di `AnalyticsExample` Xcode project  but i have this error:

![schermata 2018-07-10 alle 13 28 32](https://user-images.githubusercontent.com/6715157/42507365-3a6836be-8445-11e8-8351-5e975f8a9814.png)

**Comment by LuisRodriguezLD** [comment]
Hello, 

Just to be sure, did you run using `-DCOCOAPODS`?

**Comment by LuisRodriguezLD** [comment]
Found the problem. Using Firebase 5.X `FirebaseAnalytics/FIRApp.h` is no longer used, just remove this line and everything should work fine https://github.com/fuse-compound/Fuse.Firebase/blob/master/src/Firebase.Analytics/Analytics.uno#L54

Or you could wait to the PR containing the fix later today

**Comment by gtoto007** [comment]
Thank you 👍

**Comment by LuisRodriguezLD** [comment]
Fixed in #79
