### ISSUE TITLE
iOSHelpers fatal error: module 'Firebase' not found

### ISSUE THREAD

**Issue by treviz13** [fuse-compound/Fuse.Firebase#90]
Hey there,

With Android there was no Problem. Now I exported the Project on iOS and then there is this Error:
iOSHelpers.m:2:9: fatal error: module 'Firebase' not found

Does anyone know the solution? :/

Thanks!
Stefan

**Comment by LuisRodriguezLD** [comment]
Hello Stefan,

I have made multiple tests (even added a Travis config) and everything works. Usually that error means you are not using `-DCOCOAPODS` when building.

**Comment by treviz13** [comment]
Thank you for your reply!!! :)
But if I run with -DCOCOAPODS it doesent work :/
I am desperate :(

**Comment by LuisRodriguezLD** [comment]
That is very odd. Can I see you log?

**Comment by treviz13** [comment]
This is what I get:
`Building iOS app
.../build/iOS/Debug/src/iOSHelpers.m:2:9: fatal error: module 'Firebase' not found
** BUILD FAILED **


The following build commands failed:
	CompileC .../Objects-normal/armv7/iOSHelpers.o src/iOSHelpers.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
(unknown): E0200: iOS build failed`

**Comment by treviz13** [comment]
If I build with `fuse build -t=iOS -DCOCOAPODS` I get this Error:


> Building iOS app
> 
> Downloading dependencies
> 
> 
> [!] The Podfile does not contain any dependencies.
> 
> [!] Automatically assigning platform `ios` with version `8.0` on target `(MyProject)` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> 
> /Library/Lorse/zchain_hybrid/build/iOS/Debug/src/iOSHelpers.m:2:9: fatal error: module 'Firebase' not found
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC build/Build/Intermediates.noindex/MyProject.build/Release-iphoneos/MyProject.build/Objects-normal/armv7/iOSHelpers.o src/iOSHelpers.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> (unknown): E0200: iOS build failed
> 
> Analyzing dependencies
> Downloading dependencies
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.
>

**Comment by LuisRodriguezLD** [comment]
Maybe you missed a reference, can I see your `unoproj`?

**Comment by LuisRodriguezLD** [comment]
Travis is not having problems with building. Could be related to `COCOAPODS`, can you try reinstalling?

`sudo gem install cocoapods`

If that does not work, try building with: `--no-native`, then `cd build/iOS/debug && pod update && pod install` after that use the created .xcworkspace and let me know if xcode compiles it

**Comment by treviz13** [comment]
Thanks! I am going to try this and tell you of I have success :)

**Comment by treviz13** [comment]
When I do:
> sudo gem install cocoapods
 it says: 
> Successfully installed cocoapods-1.5.3
> Parsing documentation for cocoapods-1.5.3
> Done installing documentation for cocoapods after 2 seconds
> 1 gem installed

And when I do your other suggestion:
on pod update und pod install it says: 

> Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.
> 
> [!] The Podfile does not contain any dependencies.
> 
> [!] Automatically assigning platform `ios` with version `8.0` on target `JsonTestApp` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

with that .xcworkspace it also says "Module Firebase not found" and the error is in the IOSHelpers.m File on the line @import Firebase..

I´m desperate :(....

**Comment by LuisRodriguezLD** [comment]
Would you mind uploading your project in a .zip so I can take a look?

**Comment by treviz13** [comment]
OHHH And I thought it is there only for other use cases....I am going to try this :) 👍

**Comment by treviz13** [comment]
OMG!! It seems to be working! You are my HERO 👍 :D 
After I  have included the Firebase.Database and run "Fuse build -t=iOS -DCOCOAPODS" there is no error! 
Thank you very much for you time and your patience! :)
